apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.32.2"
  interval: 30s
  install:
    remediation:
      retries: 5
  values:
    admin:
      existingSecret: "grafana-secret"
      userKey: username
      passwordKey: password
    ingress:
      enabled: true
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana-dev.142-44-33-69.sslip.io
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-staging
        acme.cert-manager.io/http01-edit-in-place: "true"
      hosts:
        - grafana-dev.142-44-33-69.sslip.io
