apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloud-provider-osc
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/outscale-dev/cloud-provider-osc
  ref:
    branch: OSC-MIGRATION
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/
