apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: osc-bsu-csi-driver
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/outscale-dev/osc-bsu-csi-driver
  ref:
    branch: OSC-MIGRATION
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/osc-bsu-csi-driver/  
