apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "36.6.1"
  interval: 30s
  install:
    remediation:
      retries: 6
  values:
    grafana:
      admin:
        existingSecret: "grafana-secret"
        userKey: username
        passwordKey: password
      ingress:
        enabled: true
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana-dev.148-253-89-171.sslip.io
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-staging
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
          - grafana-dev.148-253-89-17.sslip.io
    prometheusOperator:
      prometheusSpec:
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: "ebs-sc"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
