apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "15.10.3"
  interval: 30s
  install:
    remediation:
      retries: 5 
  values:
    alertmanager:
      persistentVolume:
        storageClass: "ebs-sc"
    server:
      persistentVolume:
        storageClass: "ebs-sc"
    pushgateway:
      persistentVolume:
        storageClass: "ebs-sc" 
