apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-telemetry
spec:
  releaseName: open-telemetry
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry 
        namespace: flux-system
      version: "0.32.0"
  interval: 30s
  install:
    remediation:
      retries: 6
  values:
    statefulset:
      volumeClaimTemplate:
        storageClassName: "ebs-sc"        
        resources:
          requests:
            storage: 30Gi  
