apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
spec:
  releaseName: opentelemetry-collector
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: "0.32.0"
  interval: 30s
  install:
    remediation:
      retries: 6
  values:
    mode: "statefulset" 
    config:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_http:
              endpoint: 0.0.0.0:14268    
    statefulset:
      volumeClaimTemplate:
        storageClassName: "ebs-sc"        
        resources:
          requests:
            storage: 30Gi  
