apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: "0.62.0"
  interval: 30s
  install:
    remediation:
      retries: 6
  values:
    provisionDataStore:
      elasticsearch: true
      kafka: false
    elasticsearch:
      name: elasticsearch-master-credentials
      storage:
        type: elasticsearch
        elasticsearch:
          existingSecret: elasticsearch-master-credentials
          existingSecretKey: password
      volumeClaimTemplate:
        storageClassName: "ebs-sc"        
        resources:
          requests:
            storage: 30Gi        
