apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: "0.62.0"
  interval: 30s
  install:
    remediation:
      retries: 6
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
      kafka: false
    storage:
      type: elasticsearch
      elasticsearch:
        existingSecret: elasticsearch-master-credentials
        existingSecretKey: password
    elasticsearch:
      secret:
        enabled: true
      volumeClaimTemplate:
        storageClassName: "ebs-sc"        
        resources:
          requests:
            storage: 30Gi        
