apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jaeger
    meta.helm.sh/release-namespace: cluster-api-provider-outscale-system
  labels:
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jaeger
    helm.toolkit.fluxcd.io/name: jaeger
    helm.toolkit.fluxcd.io/namespace: cluster-api-provider-outscale-system
  name: opentelemetry-collector
  namespace: cluster-api-provider-outscale-system
spec:
  ports:
  - name: http-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: grpc-http
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: c-tchan-trft
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: http-c-binary-trft
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  type: ClusterIP
