apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "1.9.2"
  interval: 30s
  install:
    remediation:
      retries: 6
  values:
    expose:
      tls:
        certSource: secret
        secret:
          notarySecretName: "notary-harbor-ingress"
          secretName: "core-harbor-ingress"
      ingress:
        hosts:
          core: core.harbor-dev.148-253-103-215.sslip.io
          notary: notary.harbor-dev.148-253-103-215.sslip.io
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-staging
          acme.cert-manager.io/http01-edit-in-place: "true"
    externalURL: https://core.harbor-dev.148-253-103-215.sslip.io
    updateStrategy:
      type: Recreate
    persistence:
      enable: true
      persistentVolumeClaim:
        registry:
          storageClass: "ebs-sc"  
          size: 20Gi
        chartmuseum: 
          storageClass: "ebs-sc"
        jobservice:
          storageClass: "ebs-sc"
        database:
          storageClass: "ebs-sc"
        redis:
          storageClass: "ebs-sc"
        trivy:
          storageClass: "ebs-sc" 
