apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "1.9.2"
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    expose:
      ingress:
        hosts:
          core: core.harbor.dev
          notary: notary.harbor.dev
    persistence:
      enable: true
      persistentVolumeClaim:
        registry:
          storageClass: "ebs-sc"  
        chartmuseum: 
          storageClass: "ebs-sc"
        jobservice:
          storageClass: "ebs-sc"
        database:
          storageClass: "ebs-sc"
        redis:
          storageClass: "ebs-sc"
        trivy:
          storageClass: "ebs-sc" 
